import { solve } from '../src/solutions/day08';

const testInput = `
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
`;

describe('Day 8', () => {
  test('Part 1', () => {
    expect(solve.part1(testInput)).toBe(14);
  });

  test('Part 2', () => {
    expect(solve.part2(testInput)).toBe(34);
  });
});
